# Generated by Django 5.1.4 on 2025-08-03 11:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marquee_speed', models.PositiveIntegerField(default=50, help_text='Marquee scroll speed (pixels per second)')),
                ('marquee_pause_on_hover', models.BooleanField(default=True, help_text='Pause marquee when user hovers')),
                ('max_notifications_display', models.PositiveIntegerField(default=5, help_text='Maximum notifications to show in marquee')),
                ('show_date', models.BooleanField(default=True, help_text='Show notification date')),
                ('show_type_icon', models.BooleanField(default=True, help_text='Show type-specific icons')),
                ('enable_sound', models.BooleanField(default=False, help_text='Play sound for urgent notifications')),
                ('auto_refresh_interval', models.PositiveIntegerField(default=30, help_text='Auto-refresh interval in seconds')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error'), ('event', 'Event'), ('announcement', 'Announcement')], default='info', help_text='Type of notification for styling', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Priority affects display order', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether notification is currently displayed')),
                ('is_marquee', models.BooleanField(default=True, help_text='Include in scrolling marquee')),
                ('display_duration', models.PositiveIntegerField(default=0, help_text='Display duration in seconds (0 = permanent)')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When notification becomes active')),
                ('end_date', models.DateTimeField(blank=True, help_text='When notification expires (optional)', null=True)),
                ('action_url', models.URLField(blank=True, help_text="Optional link for 'Learn More' action", null=True)),
                ('action_text', models.CharField(blank=True, help_text='Text for action button', max_length=50, null=True)),
                ('background_color', models.CharField(default='#007bff', help_text='Background color (hex code)', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', help_text='Text color (hex code)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'is_marquee'], name='events_noti_is_acti_d73152_idx'), models.Index(fields=['start_date', 'end_date'], name='events_noti_start_d_fa93c8_idx'), models.Index(fields=['priority', 'notification_type'], name='events_noti_priorit_1d35e4_idx')],
            },
        ),
    ]
