# Generated by Django 5.1.4 on 2025-10-20 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventschedule',
            options={'ordering': ['schedule_date', 'start_time']},
        ),
        migrations.RemoveField(
            model_name='eventschedule',
            name='speaker',
        ),
        migrations.AddField(
            model_name='event',
            name='speaker_names',
            field=models.JSONField(blank=True, default=list, help_text="List of speaker names as simple text. Example: ['Dr. John Smith', 'Prof. Jane Doe']"),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='schedule_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of this schedule item'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='speaker_name',
            field=models.CharField(blank=True, help_text='Enter speaker name', max_length=200, null=True),
        ),
    ]
