# Generated by Django 5.1.4 on 2025-10-21 06:30

import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventschedule_options_and_more'),
        ('gallery', '0002_album_batch_year_alter_album_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='payment_reference',
        ),
        migrations.AddField(
            model_name='event',
            name='linked_gallery_album',
            field=models.ForeignKey(blank=True, help_text='Link this event to a gallery album', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_events', to='gallery.album'),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker_designation',
            field=models.CharField(blank=True, help_text="Speaker's designation/title", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker_details',
            field=models.TextField(blank=True, help_text='Speaker bio or details', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker_image',
            field=models.ImageField(blank=True, help_text='Upload speaker image', null=True, upload_to=events.models.event_speaker_image_upload_path),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker_name',
            field=models.CharField(blank=True, help_text='Main speaker name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_reference_id',
            field=models.CharField(blank=True, help_text='Payment reference/transaction ID - no validation, frontend handles this', max_length=100, null=True),
        ),
    ]
