# Generated by Django 5.1.4 on 2025-10-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_eventregistration_payment_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='linked_gallery_album',
        ),
        migrations.RemoveField(
            model_name='event',
            name='speaker_designation',
        ),
        migrations.RemoveField(
            model_name='event',
            name='speaker_details',
        ),
        migrations.RemoveField(
            model_name='event',
            name='speaker_image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='speaker_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='speaker_names',
        ),
    ]
