# Generated by Django 5.1.4 on 2025-10-21 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_linked_gallery_album_and_more'),
    ]

    operations = [
        # Rename title to designation in EventSpeaker
        migrations.RenameField(
            model_name='eventspeaker',
            old_name='title',
            new_name='designation',
        ),
        # Remove talk-related fields
        migrations.RemoveField(
            model_name='eventspeaker',
            name='talk_title',
        ),
        migrations.RemoveField(
            model_name='eventspeaker',
            name='talk_abstract',
        ),
        migrations.RemoveField(
            model_name='eventspeaker',
            name='talk_duration',
        ),
    ]
