# Generated by Django 5.1.4 on 2025-10-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20251021_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='dietary_requirements',
        ),
        migrations.AddField(
            model_name='event',
            name='is_food_available',
            field=models.BooleanField(default=False, help_text='Is food provided at this event?'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='food_preference',
            field=models.CharField(blank=True, choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian')], help_text='Food preference if food is available at event', max_length=10, null=True),
        ),
    ]
