# Generated by Django 5.1.4 on 2025-08-01 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(choices=[('coursera', 'Coursera'), ('edx', 'edX'), ('udemy', 'Udemy'), ('linkedin', 'LinkedIn Learning'), ('ieee', 'IEEE'), ('cisco', 'Cisco'), ('microsoft', 'Microsoft'), ('google', 'Google'), ('amazon', 'Amazon Web Services'), ('other', 'Other')], max_length=50)),
                ('certificate_type', models.CharField(choices=[('course', 'Online Course'), ('certification', 'Professional Certification'), ('workshop', 'Workshop Certificate'), ('competition', 'Competition Certificate'), ('training', 'Training Program')], default='course', max_length=20)),
                ('description', models.TextField()),
                ('duration', models.CharField(help_text='e.g., 4 weeks, 6 months', max_length=100)),
                ('prerequisites', models.TextField(blank=True, help_text='List prerequisites separated by newlines', null=True)),
                ('skills_covered', models.TextField(help_text='List skills covered separated by commas')),
                ('is_free', models.BooleanField(default=False)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('financial_aid_available', models.BooleanField(default=False)),
                ('percentage_offer', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage if any (e.g., 20.00 for 20% off)', max_digits=5, null=True)),
                ('validity_till', models.DateTimeField(blank=True, help_text='Validity date for the offer/course', null=True)),
                ('course_url', models.URLField()),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('industry_recognized', models.BooleanField(default=False)),
                ('university_credit', models.BooleanField(default=False, help_text='Check this if the certification provides university credit')),
                ('credit_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Enter credit hours ONLY if university credit is available. Leave blank if university credit is not checked.', max_digits=4, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='InternshipOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('duration', models.CharField(choices=[('less_than_month', 'Less than a month'), ('1_month', '1 Month'), ('2_months', '2 Months'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year'), ('other', 'Other')], max_length=20)),
                ('internship_type', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('stipend', 'Stipend Based')], default='stipend', max_length=20)),
                ('description', models.TextField()),
                ('requirements', models.TextField(help_text='List requirements separated by newlines')),
                ('skills', models.TextField(help_text='List skills separated by commas')),
                ('stipend_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('application_url', models.URLField()),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('certificate_provided', models.BooleanField(default=True)),
                ('letter_of_recommendation', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_internships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract')], default='full_time', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level')], default='entry', max_length=20)),
                ('description', models.TextField()),
                ('requirements', models.TextField(help_text='List requirements separated by newlines')),
                ('skills', models.TextField(help_text='List skills separated by commas')),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('application_url', models.URLField()),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
    ]
