# Generated by Django 5.1.4 on 2025-09-05 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='certificateopportunity',
            index=models.Index(fields=['certificate_type', 'provider'], name='careers_cer_certifi_a2b6ef_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateopportunity',
            index=models.Index(fields=['posted_at'], name='careers_cer_posted__2a3045_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateopportunity',
            index=models.Index(fields=['is_active'], name='careers_cer_is_acti_ca84fd_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateopportunity',
            index=models.Index(fields=['is_free'], name='careers_cer_is_free_85a51e_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateopportunity',
            index=models.Index(fields=['university_credit'], name='careers_cer_univers_bb90a8_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateopportunity',
            index=models.Index(fields=['validity_till'], name='careers_cer_validit_e63dac_idx'),
        ),
        migrations.AddIndex(
            model_name='internshipopportunity',
            index=models.Index(fields=['internship_type', 'duration'], name='careers_int_interns_7966fe_idx'),
        ),
        migrations.AddIndex(
            model_name='internshipopportunity',
            index=models.Index(fields=['posted_at'], name='careers_int_posted__af61fb_idx'),
        ),
        migrations.AddIndex(
            model_name='internshipopportunity',
            index=models.Index(fields=['is_active'], name='careers_int_is_acti_aa9c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='internshipopportunity',
            index=models.Index(fields=['company'], name='careers_int_company_c9bd9d_idx'),
        ),
        migrations.AddIndex(
            model_name='internshipopportunity',
            index=models.Index(fields=['application_deadline'], name='careers_int_applica_2c7242_idx'),
        ),
        migrations.AddIndex(
            model_name='internshipopportunity',
            index=models.Index(fields=['is_remote'], name='careers_int_is_remo_371d19_idx'),
        ),
        migrations.AddIndex(
            model_name='jobopportunity',
            index=models.Index(fields=['job_type', 'experience_level'], name='careers_job_job_typ_0244b9_idx'),
        ),
        migrations.AddIndex(
            model_name='jobopportunity',
            index=models.Index(fields=['posted_at'], name='careers_job_posted__2b18c1_idx'),
        ),
        migrations.AddIndex(
            model_name='jobopportunity',
            index=models.Index(fields=['is_active'], name='careers_job_is_acti_863a31_idx'),
        ),
        migrations.AddIndex(
            model_name='jobopportunity',
            index=models.Index(fields=['company'], name='careers_job_company_b5de0c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobopportunity',
            index=models.Index(fields=['application_deadline'], name='careers_job_applica_d65329_idx'),
        ),
    ]
