# Generated by Django 5.1.4 on 2025-07-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipopportunity',
            name='duration',
            field=models.CharField(choices=[('less_than_month', 'Less than a month'), ('1_month', '1 Month'), ('2_months', '2 Months'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year'), ('other', 'Other')], max_length=20),
        ),
    ]
