# Generated by Django 5.1.4 on 2025-08-03 05:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Full name of the alumni', max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('alternative_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('student_id', models.CharField(blank=True, help_text='Original student ID', max_length=20, null=True)),
                ('scheme', models.PositiveIntegerField(blank=True, help_text='Academic scheme year (e.g., 2019, 2021)', null=True)),
                ('year_of_joining', models.PositiveIntegerField(help_text='Year joined the institution')),
                ('year_of_passout', models.PositiveIntegerField(help_text='Year of graduation')),
                ('department', models.CharField(default='Electrical and Electronics Engineering', editable=False, max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('job_title', models.CharField(blank=True, help_text='Current job title or designation', max_length=150, null=True)),
                ('current_company', models.CharField(blank=True, max_length=200, null=True)),
                ('current_location', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self Employed'), ('unemployed', 'Unemployed'), ('higher_studies', 'Higher Studies'), ('entrepreneur', 'Entrepreneur'), ('other', 'Other')], default='employed', max_length=20)),
                ('achievements', models.TextField(blank=True, help_text='Notable achievements or awards', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Feedback about the institution', null=True)),
                ('willing_to_mentor', models.BooleanField(default=False)),
                ('allow_contact_from_juniors', models.BooleanField(default=True)),
                ('newsletter_subscription', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Email verification status')),
                ('is_active', models.BooleanField(default=True, help_text='Active status in alumni network')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alumni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alumni',
                'verbose_name_plural': 'Alumni',
                'ordering': ['-year_of_passout', 'full_name'],
                'indexes': [models.Index(fields=['year_of_passout', 'department'], name='alumni_alum_year_of_e2428b_idx'), models.Index(fields=['scheme', 'year_of_joining'], name='alumni_alum_scheme_5edf2f_idx'), models.Index(fields=['employment_status'], name='alumni_alum_employm_ad4c16_idx'), models.Index(fields=['current_company'], name='alumni_alum_current_060909_idx'), models.Index(fields=['email'], name='alumni_alum_email_5ff8f4_idx')],
            },
        ),
    ]
