# Generated by Django 5.1.4 on 2025-09-05 13:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumni', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_year_range', models.CharField(help_text="Batch year range (e.g., '2022-2026', '2023-2027')", max_length=20, unique=True)),
                ('batch_name', models.CharField(help_text="e.g., 'Batch 2022-2026', 'Class of 2026'", max_length=100)),
                ('batch_description', models.TextField(blank=True, help_text='Description of the batch', null=True)),
                ('total_alumni', models.IntegerField(default=0, help_text='Total number of alumni in this batch')),
                ('verified_alumni', models.IntegerField(default=0, help_text='Number of verified alumni in this batch')),
                ('batch_group_photo', models.ImageField(blank=True, help_text='Official graduation/group photo of the batch', null=True, upload_to='alumni/batch_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alumni Batch',
                'verbose_name_plural': 'Alumni Batches',
                'ordering': ['-batch_year_range'],
            },
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Full name of the alumni', max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('job_title', models.CharField(blank=True, help_text='Current job title or designation', max_length=150, null=True)),
                ('current_company', models.CharField(blank=True, max_length=200, null=True)),
                ('current_location', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self Employed'), ('unemployed', 'Unemployed'), ('higher_studies', 'Higher Studies'), ('entrepreneur', 'Entrepreneur'), ('other', 'Other')], default='employed', max_length=20)),
                ('achievements', models.TextField(blank=True, help_text='Notable achievements or awards', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Feedback about the institution', null=True)),
                ('willing_to_mentor', models.BooleanField(default=False)),
                ('allow_contact_from_juniors', models.BooleanField(default=True)),
                ('newsletter_subscription', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Email verification status')),
                ('is_active', models.BooleanField(default=True, help_text='Active status in alumni network')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alumni', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, help_text='Select the batch this alumni belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumni_members', to='alumni.alumnibatch')),
            ],
            options={
                'verbose_name': 'Alumni',
                'verbose_name_plural': 'Alumni',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['batch'], name='alumni_alum_batch_i_ddae27_idx'), models.Index(fields=['employment_status'], name='alumni_alum_employm_ad4c16_idx'), models.Index(fields=['current_company'], name='alumni_alum_current_060909_idx'), models.Index(fields=['email'], name='alumni_alum_email_5ff8f4_idx')],
            },
        ),
    ]
