# Generated by Django 5.1.4 on 2025-07-20 05:53

from django.db import migrations, models


def update_department_names(apps, schema_editor):
    """Update existing records to use the new department name"""
    Alumni = apps.get_model('alumni', 'Alumni')
    Alumni.objects.filter(department='Electronics Engineering').update(
        department='Electrical and Electronics Engineering'
    )


def reverse_update_department_names(apps, schema_editor):
    """Reverse the department name update"""
    Alumni = apps.get_model('alumni', 'Alumni')
    Alumni.objects.filter(department='Electrical and Electronics Engineering').update(
        department='Electronics Engineering'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        # Update existing records
        migrations.RunPython(update_department_names, reverse_update_department_names),
        
        # Update the default value for new records
        migrations.AlterField(
            model_name='alumni',
            name='department',
            field=models.CharField(default='Electrical and Electronics Engineering', editable=False, max_length=100),
        ),
    ]
