# Generated by Django 5.1.4 on 2025-09-05 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='projects_pr_created_6b02e3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['student_batch'], name='projects_pr_student_dbf367_idx'),
        ),
        migrations.AddIndex(
            model_name='projectimage',
            index=models.Index(fields=['project', 'is_featured'], name='projects_pr_project_da66cc_idx'),
        ),
        migrations.AddIndex(
            model_name='projectimage',
            index=models.Index(fields=['created_at'], name='projects_pr_created_18f50d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectvideo',
            index=models.Index(fields=['project', 'is_featured'], name='projects_pr_project_0c5380_idx'),
        ),
        migrations.AddIndex(
            model_name='projectvideo',
            index=models.Index(fields=['created_at'], name='projects_pr_created_c580e9_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['project', 'name'], name='projects_te_project_cefbe5_idx'),
        ),
    ]
