# Generated by Django 5.1.4 on 2025-08-05 14:06

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_images',
            field=models.ImageField(blank=True, help_text='Main cover image for the project - this will be used as the thumbnail in project lists and cards', null=True, upload_to=projects.models.project_image_upload_path),
        ),
    ]
