# Generated by Django 5.1.4 on 2025-10-20 09:55

import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_projects_pr_created_6b02e3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_images',
        ),
        migrations.AddField(
            model_name='project',
            name='academic_year',
            field=models.CharField(blank=True, help_text='e.g., 2024, 2023', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, help_text='Main project image for detailed view (fallback if thumbnail not provided)', null=True, upload_to=projects.models.project_image_upload_path),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image for project cards and listings (recommended: 800x600px)', null=True, upload_to=projects.models.project_thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_report',
            field=models.FileField(blank=True, help_text='Upload project report (PDF/DOC/DOCX). Maximum file size: 15MB.', null=True, upload_to=projects.models.project_report_upload_path),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['academic_year'], name='projects_pr_academi_95fbf3_idx'),
        ),
    ]
