# Generated by Django 5.1.4 on 2025-10-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_project_images_project_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='caption',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, help_text='e.g., Frontend Developer, UI Designer', max_length=200, null=True),
        ),
    ]
