services:
  # Django Web Service
  - type: web
    name: eesa-college-portal
    env: python3
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn eesa_backend.wsgi:application --bind 0.0.0.0:$PORT
    buildFilter:
      paths:
        - requirements.txt
        - eesa_backend/**
        - accounts/**
        - academics/**
        - alumni/**
        - careers/**
        - events/**
        - gallery/**
        - placements/**
        - projects/**
        - manage.py
      - key: CLOUDINARY_URL
        sync: false
      - key: DISABLE_COLLECTSTATIC
        value: "0"
      - key: DJANGO_SETTINGS_MODULE
        value: "eesa_backend.settings"
      - key: CORS_ALLOWED_ORIGINS
        sync: false
