# Generated by Django 5.1.4 on 2025-09-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='batch_year',
            field=models.PositiveIntegerField(blank=True, help_text='Graduation year for alumni albums (required for Alumni albums)', null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='type',
            field=models.CharField(choices=[('eesa', 'EESA Program'), ('general', 'General Program'), ('alumni', 'Alumni Batch')], max_length=10),
        ),
    ]
