# Generated by Django 5.1.4 on 2025-07-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementdrive',
            name='required_documents',
            field=models.TextField(blank=True, help_text='List of required documents, one per line'),
        ),
    ]
