# Generated by Django 5.1.4 on 2025-09-05 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='placements__name_1860ca_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['industry'], name='placements__industr_b985fe_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active', 'is_verified'], name='placements__is_acti_41866a_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['created_at'], name='placements__created_6116f1_idx'),
        ),
        migrations.AddIndex(
            model_name='placedstudent',
            index=models.Index(fields=['company', 'batch_year'], name='placements__company_8f600e_idx'),
        ),
        migrations.AddIndex(
            model_name='placedstudent',
            index=models.Index(fields=['offer_date'], name='placements__offer_d_f1d1bf_idx'),
        ),
        migrations.AddIndex(
            model_name='placedstudent',
            index=models.Index(fields=['package_lpa'], name='placements__package_e1c8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='placedstudent',
            index=models.Index(fields=['job_type', 'category'], name='placements__job_typ_e5076a_idx'),
        ),
        migrations.AddIndex(
            model_name='placedstudent',
            index=models.Index(fields=['is_verified', 'is_active'], name='placements__is_veri_aaa94d_idx'),
        ),
        migrations.AddIndex(
            model_name='placementapplication',
            index=models.Index(fields=['drive', 'status'], name='placements__drive_i_340a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='placementapplication',
            index=models.Index(fields=['student', 'status'], name='placements__student_9bc49d_idx'),
        ),
        migrations.AddIndex(
            model_name='placementapplication',
            index=models.Index(fields=['applied_at'], name='placements__applied_1d1ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='placementapplication',
            index=models.Index(fields=['result_status'], name='placements__result__a7b4ce_idx'),
        ),
        migrations.AddIndex(
            model_name='placementbrochure',
            index=models.Index(fields=['academic_year'], name='placements__academi_b13c82_idx'),
        ),
        migrations.AddIndex(
            model_name='placementbrochure',
            index=models.Index(fields=['is_current'], name='placements__is_curr_da64e4_idx'),
        ),
        migrations.AddIndex(
            model_name='placementdrive',
            index=models.Index(fields=['company', 'job_type'], name='placements__company_82be94_idx'),
        ),
        migrations.AddIndex(
            model_name='placementdrive',
            index=models.Index(fields=['drive_date'], name='placements__drive_d_4927d6_idx'),
        ),
        migrations.AddIndex(
            model_name='placementdrive',
            index=models.Index(fields=['registration_start', 'registration_end'], name='placements__registr_e1f059_idx'),
        ),
        migrations.AddIndex(
            model_name='placementdrive',
            index=models.Index(fields=['is_active', 'is_featured'], name='placements__is_acti_ec0b20_idx'),
        ),
        migrations.AddIndex(
            model_name='placementdrive',
            index=models.Index(fields=['min_cgpa'], name='placements__min_cgp_b9fa42_idx'),
        ),
        migrations.AddIndex(
            model_name='placementstatistics',
            index=models.Index(fields=['academic_year', 'batch_year'], name='placements__academi_17e7df_idx'),
        ),
        migrations.AddIndex(
            model_name='placementstatistics',
            index=models.Index(fields=['branch'], name='placements__branch_3649f4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcoordinator',
            index=models.Index(fields=['is_active', 'display_order'], name='placements__is_acti_8055f9_idx'),
        ),
    ]
