# Generated by Django 5.1.4 on 2025-07-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('faculty_coordinator', 'Faculty Coordinator'), ('events_head', 'Events Head'), ('placement_coordinator', 'Placement Coordinator'), ('alumni_head', 'Alumni Head'), ('tech_head', 'Tech Head'), ('admin', 'Admin')], help_text='User role for permission assignment', max_length=50, null=True),
        ),
    ]
