# Generated by Django 5.1.4 on 2025-08-03 05:30

import academics.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('notes', 'Notes'), ('textbook', 'Textbooks'), ('pyq', 'Previous Year Questions'), ('regulations', 'Regulations'), ('syllabus', 'Syllabus')], max_length=20)),
                ('file', models.FileField(help_text='Upload only PDF files. Maximum file size: 15MB.', max_length=255, upload_to=academics.models.academic_resource_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('module_number', models.PositiveIntegerField(choices=[(1, 'Module 1'), (2, 'Module 2'), (3, 'Module 3'), (4, 'Module 4'), (5, 'Module 5'), (0, 'General/Complete')], default=0, help_text='Module number (only for notes)')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(help_text="e.g., 'Scheme 2018', 'CBCS 2022'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')])),
                ('department', models.CharField(choices=[('EEE', 'Electrical & Electronics Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('IT', 'Information Technology Engineering'), ('CS', 'Computer Science & Engineering'), ('ME', 'Mechanical Engineering'), ('SFE', 'Safety & Fire Engineering'), ('CE', 'Civil Engineering')], default='EEE', max_length=10)),
                ('credits', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scheme__year', 'semester', 'name'],
            },
        ),
    ]
