# Generated by Django 5.1.4 on 2025-07-19 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicresource',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicresource',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academics.academiccategory'),
        ),
        migrations.AddField(
            model_name='academicresource',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcedownload',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='academics.academicresource'),
        ),
        migrations.AddField(
            model_name='resourcedownload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.scheme'),
        ),
        migrations.AddField(
            model_name='academicresource',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcedownload',
            unique_together={('resource', 'user', 'downloaded_at')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['scheme', 'semester'], name='academics_s_scheme__83f4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='academics_s_code_3689e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('code', 'scheme', 'semester')},
        ),
        migrations.AddIndex(
            model_name='academicresource',
            index=models.Index(fields=['category', 'subject', 'is_approved'], name='academics_a_categor_b2f4cc_idx'),
        ),
        migrations.AddIndex(
            model_name='academicresource',
            index=models.Index(fields=['uploaded_by'], name='academics_a_uploade_3b927c_idx'),
        ),
        migrations.AddIndex(
            model_name='academicresource',
            index=models.Index(fields=['category', 'module_number'], name='academics_a_categor_286cee_idx'),
        ),
        migrations.AddIndex(
            model_name='academicresource',
            index=models.Index(fields=['exam_type', 'exam_year'], name='academics_a_exam_ty_6eac64_idx'),
        ),
    ]
