# Generated by Django 5.1.4 on 2025-08-03 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicresource',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicresource',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcelike',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='academics.academicresource'),
        ),
        migrations.AddField(
            model_name='subject',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.scheme'),
        ),
        migrations.AddField(
            model_name='academicresource',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academics.subject'),
        ),
        migrations.AddIndex(
            model_name='resourcelike',
            index=models.Index(fields=['resource', 'ip_address'], name='academics_r_resourc_b48921_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcelike',
            index=models.Index(fields=['created_at'], name='academics_r_created_bab5cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcelike',
            unique_together={('resource', 'ip_address')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['scheme', 'semester'], name='academics_s_scheme__83f4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='academics_s_code_3689e5_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['department'], name='academics_s_departm_db081c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('code', 'scheme', 'semester')},
        ),
        migrations.AddIndex(
            model_name='academicresource',
            index=models.Index(fields=['category', 'subject'], name='academics_a_categor_682cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='academicresource',
            index=models.Index(fields=['uploaded_by'], name='academics_a_uploade_3b927c_idx'),
        ),
        migrations.AddIndex(
            model_name='academicresource',
            index=models.Index(fields=['is_approved'], name='academics_a_is_appr_0bc707_idx'),
        ),
        migrations.AddIndex(
            model_name='academicresource',
            index=models.Index(fields=['created_at'], name='academics_a_created_4fe3a1_idx'),
        ),
    ]
