# Generated by Django 5.1.4 on 2025-07-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccategory',
            name='category_type',
            field=models.CharField(choices=[('notes', 'Notes'), ('textbook', 'Textbooks'), ('pyq', 'Previous Year Questions'), ('regulations', 'Regulations'), ('syllabus', 'Syllabus')], max_length=20),
        ),
    ]
