# Generated by Django 5.1.4 on 2025-07-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicresource_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicresource',
            name='department',
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.CharField(choices=[('EEE', 'Electrical & Electronics Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('IT', 'Information Technology'), ('CS', 'Computer Science & Engineering'), ('ME', 'Mechanical Engineering'), ('SFE', 'Safety & Fire Engineering'), ('CE', 'Civil Engineering')], default='EEE', help_text='Department for this subject', max_length=10),
        ),
    ]
