# Generated by Django 5.1.4 on 2025-07-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_add_regulations_syllabus_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicresource',
            name='category',
            field=models.CharField(choices=[('notes', 'Notes'), ('textbook', 'Textbooks'), ('pyq', 'Previous Year Questions'), ('regulations', 'Regulations'), ('syllabus', 'Syllabus')], max_length=20),
        ),
        migrations.RenameIndex(
            model_name='academicresource',
            new_name='academics_a_categor_2aeb62_idx',
            old_name='academics_a_categor_b2f4cc_idx',
        ),
        migrations.RenameIndex(
            model_name='academicresource',
            new_name='academics_a_categor_7d9571_idx',
            old_name='academics_a_categor_286cee_idx',
        ),
        migrations.DeleteModel(
            name='AcademicCategory',
        ),
    ]
