# Generated by Django 5.1.4 on 2025-07-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_academicresource_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.CharField(choices=[('EEE', 'Electrical & Electronics Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('IT', 'Information Technology Engineering'), ('CS', 'Computer Science & Engineering'), ('ME', 'Mechanical Engineering'), ('SFE', 'Safety & Fire Engineering'), ('CE', 'Civil Engineering')], default='EEE', help_text='Department for this subject', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')]),
        ),
    ]
