# Generated by Django 5.1.4 on 2025-07-27 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_subject_department_alter_subject_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicresource',
            old_name='view_count',
            new_name='like_count',
        ),
        migrations.CreateModel(
            name='ResourceLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='academics.academicresource')),
            ],
            options={
                'indexes': [models.Index(fields=['resource', 'ip_address'], name='academics_r_resourc_b48921_idx'), models.Index(fields=['created_at'], name='academics_r_created_bab5cb_idx')],
                'unique_together': {('resource', 'ip_address')},
            },
        ),
    ]
