# Generated by Django 5.1.4 on 2025-07-27 14:44

import academics.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_rename_view_count_academicresource_like_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourcedownload',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='resourcedownload',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resourcedownload',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='academicresource',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='academicresource',
            name='academics_a_categor_2aeb62_idx',
        ),
        migrations.RemoveIndex(
            model_name='academicresource',
            name='academics_a_categor_7d9571_idx',
        ),
        migrations.RemoveIndex(
            model_name='academicresource',
            name='academics_a_exam_ty_6eac64_idx',
        ),
        migrations.RemoveField(
            model_name='academicresource',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='academicresource',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='academicresource',
            name='author',
        ),
        migrations.RemoveField(
            model_name='academicresource',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='academicresource',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='academicresource',
            name='exam_year',
        ),
        migrations.RemoveField(
            model_name='academicresource',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='academicresource',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='academicresource',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='academicresource',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='description',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='academicresource',
            name='file',
            field=models.FileField(help_text='Upload only PDF files. Maximum file size: 15MB.', upload_to=academics.models.academic_resource_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='academicresource',
            name='module_number',
            field=models.PositiveIntegerField(choices=[(1, 'Module 1'), (2, 'Module 2'), (3, 'Module 3'), (4, 'Module 4'), (5, 'Module 5'), (0, 'General/Complete')], default=0, help_text='Module number (only for notes)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.CharField(choices=[('EEE', 'Electrical & Electronics Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('IT', 'Information Technology Engineering'), ('CS', 'Computer Science & Engineering'), ('ME', 'Mechanical Engineering'), ('SFE', 'Safety & Fire Engineering'), ('CE', 'Civil Engineering')], default='EEE', max_length=10),
        ),
        migrations.AddIndex(
            model_name='academicresource',
            index=models.Index(fields=['category', 'subject'], name='academics_a_categor_682cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='academicresource',
            index=models.Index(fields=['is_approved'], name='academics_a_is_appr_0bc707_idx'),
        ),
        migrations.AddIndex(
            model_name='academicresource',
            index=models.Index(fields=['created_at'], name='academics_a_created_4fe3a1_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['department'], name='academics_s_departm_db081c_idx'),
        ),
        migrations.DeleteModel(
            name='ResourceDownload',
        ),
    ]
