# Generated by Django 5.1.4 on 2025-09-05 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_enhanced_production_indexing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='academicresource',
            name='academics_a_is_appr_0bc707_idx',
        ),
        migrations.RemoveField(
            model_name='academicresource',
            name='search_vector',
        ),
        migrations.AddIndex(
            model_name='academicresource',
            index=models.Index(fields=['subject', 'is_approved', 'is_active'], name='academics_a_subject_f56e79_idx'),
        ),
        migrations.AddIndex(
            model_name='academicresource',
            index=models.Index(fields=['is_approved', 'is_active'], name='academics_a_is_appr_52fe85_idx'),
        ),
        migrations.AddIndex(
            model_name='academicresource',
            index=models.Index(fields=['subject', 'category', 'module_number'], name='academics_a_subject_7d1417_idx'),
        ),
        migrations.AddIndex(
            model_name='academicresource',
            index=models.Index(fields=['category', 'is_approved'], name='academics_a_categor_fc0ead_idx'),
        ),
        migrations.AddIndex(
            model_name='academicresource',
            index=models.Index(fields=['download_count'], name='academics_a_downloa_247418_idx'),
        ),
        migrations.AddIndex(
            model_name='academicresource',
            index=models.Index(fields=['like_count'], name='academics_a_like_co_99aa75_idx'),
        ),
        migrations.AddIndex(
            model_name='academicresource',
            index=models.Index(fields=['subject', 'category'], name='idx_academics_subject_category'),
        ),
        migrations.AddIndex(
            model_name='scheme',
            index=models.Index(fields=['year'], name='academics_s_year_a0bed5_idx'),
        ),
        migrations.AddIndex(
            model_name='scheme',
            index=models.Index(fields=['is_active'], name='academics_s_is_acti_ebd3a2_idx'),
        ),
    ]
