# Generated by Django 5.1.4 on 2025-09-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_remove_academicresource_academics_a_is_appr_0bc707_idx_and_more'),
    ]

    operations = [
        # Clean up the PostgreSQL trigger and function that references non-existent search_vector field
        migrations.RunSQL(
            sql=[
                "DROP TRIGGER IF EXISTS update_academic_search_vector_trigger ON academics_academicresource;",
                "DROP FUNCTION IF EXISTS update_academic_search_vector();",
            ],
            reverse_sql=[
                # No reverse - we don't want to recreate the broken trigger
            ]
        ),
    ]
