# Generated by Django 5.1.4 on 2025-07-27 18:57

import academics.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_academicresource_approved_by_subject_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicresource',
            name='file',
            field=models.FileField(help_text='Upload only PDF files. Maximum file size: 15MB.', max_length=255, upload_to=academics.models.academic_resource_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
